### ISSUE TITLE
Err logs when Destroy Items modded

### ISSUE THREAD

**Issue by TangoWorks** [GarwelGarwel/DestroyItem#4]
I added Destroy Item and the err log prompted.The log disappeared after removing the mod.Here is the log:(Using Rimpy Mod Manager to sort the mods)
[errlogs.txt](https://github.com/GarwelGarwel/DestroyItem/files/10419714/errlogs.txt)

**Comment by GarwelGarwel** [comment]
I need the Player.log file, and could you please enable debug logging in the mod settings first.

**Comment by TangoWorks** [comment]
Ok,I enabled the dev mode,and with DI modded,run the game.Here's my newly generated player.log file:
[Player.log](https://github.com/GarwelGarwel/DestroyItem/files/10419979/Player.log)

**Comment by GarwelGarwel** [comment]
Thanks. Apparently, the reason is you don't have Ideology DLC and I'm not handling it correctly. Will fix it in the next release. I suppose this is only log error spam, and the game plays correctly otherwise?

**Comment by TangoWorks** [comment]
> 

Got it.Currently I simply remove the DI mod to play correctly.Maybe I need to purchase the Ideo DLC later.(I play Vanilla game  with mods.)

**Comment by GarwelGarwel** [comment]
I think you can just ignore the errors for now, they shouldn't affect gameplay (that's my theory at least).

**Comment by TangoWorks** [comment]
Yes,I played the game with DI modded just now.Although there's still error logs in the main menu screen,the gameplay of the existing savegame is ok.The in-game 'Destroy Item'  Order works well.

**Comment by GarwelGarwel** [comment]
Fixed in v1.0.8
